#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 28, 2020 05:53:59 PM +0700  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m43" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 968x733+459+148
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1055
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m43
    menu $site_3_0 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    labelframe $top.lab44 \
        -font TkDefaultFont -foreground black -text Email \
        -background $vTcl(actual_gui_bg) -height 705 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 930 
    vTcl:DefineAlias "$top.lab44" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab44
    labelframe $site_3_0.lab45 \
        -font TkDefaultFont -foreground black -text {Mail Info} \
        -background $vTcl(actual_gui_bg) -height 205 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 900 
    vTcl:DefineAlias "$site_3_0.lab45" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab45
    label $site_4_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text From 
    vTcl:DefineAlias "$site_4_0.lab46" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text To 
    vTcl:DefineAlias "$site_4_0.lab47" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_4_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Subject 
    vTcl:DefineAlias "$site_4_0.lab48" "Label3" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_4_0.lab52 \
        -font TkDefaultFont -foreground black -text Status \
        -background $vTcl(actual_gui_bg) -height 115 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 380 
    vTcl:DefineAlias "$site_4_0.lab52" "Labelframe3" vTcl:WidgetProc "Toplevel1" 1
    set site_5_0 $site_4_0.lab52
    label $site_5_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Baca 
    vTcl:DefineAlias "$site_5_0.lab53" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Label 
    vTcl:DefineAlias "$site_5_0.lab54" "Label5" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab55 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Kategori 
    vTcl:DefineAlias "$site_5_0.lab55" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent60 \
        -background white -disabledbackground #f0f0f0f0f0f0 \
        -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent60" "statusBaca" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent61 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent61" "statusKategori" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent62 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_5_0.ent62" "statusLabel" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab53 \
        -in $site_5_0 -x 30 -y 20 -anchor nw -bordermode ignore 
    place $site_5_0.lab54 \
        -in $site_5_0 -x 30 -y 80 -anchor nw -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 30 -y 50 -anchor nw -bordermode ignore 
    place $site_5_0.ent60 \
        -in $site_5_0 -x 110 -y 20 -width 254 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent61 \
        -in $site_5_0 -x 110 -y 50 -width 254 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.ent62 \
        -in $site_5_0 -x 110 -y 80 -width 254 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    entry $site_4_0.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent56" "From" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent57" "To" vTcl:WidgetProc "Toplevel1" 1
    text $site_4_0.tex67 \
        -background white -font TkTextFont -foreground black -height 44 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -width 764 -wrap word 
    .top42.lab44.lab45.tex67 configure -font "TkTextFont"
    .top42.lab44.lab45.tex67 insert end text
    vTcl:DefineAlias "$site_4_0.tex67" "Subject" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.lab46 \
        -in $site_4_0 -x 40 -y 50 -anchor nw -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 40 -y 100 -anchor nw -bordermode ignore 
    place $site_4_0.lab48 \
        -in $site_4_0 -x 40 -y 150 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 480 -y 20 -width 380 -relwidth 0 -height 115 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent56 \
        -in $site_4_0 -x 100 -y 50 -width 334 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent57 \
        -in $site_4_0 -x 100 -y 100 -width 334 -relwidth 0 -height 24 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex67 \
        -in $site_4_0 -x 100 -y 150 -width 764 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $site_3_0.lab63 \
        -font TkDefaultFont -foreground black -text {Isi E-Mail} \
        -background $vTcl(actual_gui_bg) -height 465 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 900 
    vTcl:DefineAlias "$site_3_0.lab63" "Labelframe4" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab63
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_4_0.scr66 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_4_0.scr66" "Mail" vTcl:WidgetProc "Toplevel1" 1

    $site_4_0.scr66.01 configure -background white \
        -font TkTextFont \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap none
    place $site_4_0.scr66 \
        -in $site_4_0 -x 10 -y 30 -width 875 -relwidth 0 -height 424 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 20 -width 900 -relwidth 0 -height 205 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 20 -y 230 -width 900 -relwidth 0 -height 465 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab44 \
        -in $top -x 20 -y 10 -width 930 -relwidth 0 -height 705 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

