#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 28, 2020 05:53:57 PM +0700  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import View_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    View_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    View_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None,From='Herlangga72@gmail.com'):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("968x733+459+148")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Mail")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.021, rely=0.014, relheight=0.962
                , relwidth=0.961)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''Email''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")

        self.Labelframe2 = tk.LabelFrame(self.Labelframe1)
        self.Labelframe2.place(relx=0.022, rely=0.028, relheight=0.291
                , relwidth=0.968, bordermode='ignore')
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Mail Info''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Labelframe2)
        self.Label1.place(relx=0.044, rely=0.244, height=26, width=40
                , bordermode='ignore')
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''From''')

        self.Label2 = tk.Label(self.Labelframe2)
        self.Label2.place(relx=0.044, rely=0.488, height=26, width=23
                , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''To''')

        self.Label3 = tk.Label(self.Labelframe2)
        self.Label3.place(relx=0.044, rely=0.732, height=26, width=55
                , bordermode='ignore')
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Subject''')

        self.Labelframe3 = tk.LabelFrame(self.Labelframe2)
        self.Labelframe3.place(relx=0.533, rely=0.098, relheight=0.561
                , relwidth=0.422, bordermode='ignore')
        self.Labelframe3.configure(relief='groove')
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Status''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")

        self.Label4 = tk.Label(self.Labelframe3)
        self.Label4.place(relx=0.079, rely=0.174, height=26, width=38
                , bordermode='ignore')
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Baca''')

        self.Label5 = tk.Label(self.Labelframe3)
        self.Label5.place(relx=0.079, rely=0.696, height=26, width=42
                , bordermode='ignore')
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Label''')

        self.Label6 = tk.Label(self.Labelframe3)
        self.Label6.place(relx=0.079, rely=0.435, height=26, width=63
                , bordermode='ignore')
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(text='''Kategori''')

        self.statusBaca = tk.Entry(self.Labelframe3)
        self.statusBaca.place(relx=0.289, rely=0.174, height=24, relwidth=0.668
                , bordermode='ignore')
        self.statusBaca.configure(background="white")
        self.statusBaca.configure(disabledbackground="#f0f0f0f0f0f0")
        self.statusBaca.configure(disabledforeground="#a3a3a3")
        self.statusBaca.configure(font="TkFixedFont")
        self.statusBaca.configure(foreground="#000000")
        self.statusBaca.configure(highlightbackground="#d9d9d9")
        self.statusBaca.configure(highlightcolor="black")
        self.statusBaca.configure(insertbackground="black")
        self.statusBaca.configure(selectbackground="#c4c4c4")
        self.statusBaca.configure(selectforeground="black")
        self.statusBaca.insert('end','%s'%From)
        self.statusBaca.configure(state='disable')
        
        self.statusKategori = tk.Entry(self.Labelframe3)
        self.statusKategori.place(relx=0.289, rely=0.435, height=24
                , relwidth=0.668, bordermode='ignore')
        self.statusKategori.configure(background="white")
        self.statusKategori.configure(disabledforeground="#a3a3a3")
        self.statusKategori.configure(font="TkFixedFont")
        self.statusKategori.configure(foreground="#000000")
        self.statusKategori.configure(highlightbackground="#d9d9d9")
        self.statusKategori.configure(highlightcolor="black")
        self.statusKategori.configure(insertbackground="black")
        self.statusKategori.configure(selectbackground="#c4c4c4")
        self.statusKategori.configure(selectforeground="black")
        self.statusKategori.insert('end','%s'%From)
        self.statusKategori.configure(state='disable')
        
        self.statusLabel = tk.Entry(self.Labelframe3)
        self.statusLabel.place(relx=0.289, rely=0.696, height=24, relwidth=0.668
                , bordermode='ignore')
        self.statusLabel.configure(background="white")
        self.statusLabel.configure(disabledforeground="#a3a3a3")
        self.statusLabel.configure(font="TkFixedFont")
        self.statusLabel.configure(foreground="#000000")
        self.statusLabel.configure(highlightbackground="#d9d9d9")
        self.statusLabel.configure(highlightcolor="black")
        self.statusLabel.configure(insertbackground="black")
        self.statusLabel.configure(selectbackground="#c4c4c4")
        self.statusLabel.configure(selectforeground="black")
        self.statusLabel.insert('end','%s'%From)
        self.statusLabel.configure(state='disable')
        
        self.From = tk.Entry(self.Labelframe2)
        self.From.place(relx=0.111, rely=0.244, height=24, relwidth=0.371
                , bordermode='ignore')
        self.From.configure(background="white")
        self.From.configure(disabledforeground="#a3a3a3")
        self.From.configure(font="TkFixedFont")
        self.From.configure(foreground="#000000")
        self.From.configure(highlightbackground="#d9d9d9")
        self.From.configure(highlightcolor="black")
        self.From.configure(insertbackground="black")
        self.From.configure(selectbackground="#c4c4c4")
        self.From.configure(selectforeground="black")
        self.From.insert('end','%s'%From)
        self.From.configure(state='disable')
        
        self.To = tk.Entry(self.Labelframe2)
        self.To.place(relx=0.111, rely=0.488, height=24, relwidth=0.371
                , bordermode='ignore')
        self.To.configure(background="white")
        self.To.configure(disabledforeground="#a3a3a3")
        self.To.configure(font="TkFixedFont")
        self.To.configure(foreground="#000000")
        self.To.configure(highlightbackground="#d9d9d9")
        self.To.configure(highlightcolor="black")
        self.To.configure(insertbackground="black")
        self.To.configure(selectbackground="#c4c4c4")
        self.To.configure(selectforeground="black")
        self.To.insert('end','%s'%From)
        self.To.configure(state='disable')
        
        self.Subject = tk.Text(self.Labelframe2)
        self.Subject.place(relx=0.111, rely=0.732, relheight=0.215
                , relwidth=0.849, bordermode='ignore')
        self.Subject.configure(background="white")
        self.Subject.configure(font="TkTextFont")
        self.Subject.configure(foreground="black")
        self.Subject.configure(highlightbackground="#d9d9d9")
        self.Subject.configure(highlightcolor="black")
        self.Subject.configure(insertbackground="black")
        self.Subject.configure(selectbackground="#c4c4c4")
        self.Subject.configure(selectforeground="black")
        self.Subject.configure(wrap="word")
        self.Subject.insert('end','%s'%From)
        self.Subject.configure(state='disable')
        
        self.Labelframe4 = tk.LabelFrame(self.Labelframe1)
        self.Labelframe4.place(relx=0.022, rely=0.326, relheight=0.66
                , relwidth=0.968, bordermode='ignore')
        self.Labelframe4.configure(relief='groove')
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''Isi E-Mail''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")

        self.Mail = ScrolledText(self.Labelframe4)
        self.Mail.place(relx=0.011, rely=0.065, relheight=0.912, relwidth=0.972
                , bordermode='ignore')
        self.Mail.configure(background="white")
        self.Mail.configure(font="TkTextFont")
        self.Mail.configure(foreground="black")
        self.Mail.configure(highlightbackground="#d9d9d9")
        self.Mail.configure(highlightcolor="black")
        self.Mail.configure(insertbackground="black")
        self.Mail.configure(insertborderwidth="3")
        self.Mail.configure(selectbackground="#c4c4c4")
        self.Mail.configure(selectforeground="black")
        self.Mail.configure(wrap="none")
        self.Mail.insert('end','%s'%From)
        self.Mail.configure(state='disable')
        
# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = tk.Pack.__dict__.keys() | tk.Grid.__dict__.keys() \
                  | tk.Place.__dict__.keys()
        else:
            methods = tk.Pack.__dict__.keys() + tk.Grid.__dict__.keys() \
                  + tk.Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        container.bind('<Enter>', lambda e: _bound_to_mousewheel(e, container))
        container.bind('<Leave>', lambda e: _unbound_to_mousewheel(e, container))
        return func(cls, container, **kw)
    return wrapped

class ScrolledText(AutoScroll, tk.Text):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        tk.Text.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

import platform
def _bound_to_mousewheel(event, widget):
    child = widget.winfo_children()[0]
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        child.bind_all('<MouseWheel>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-MouseWheel>', lambda e: _on_shiftmouse(e, child))
    else:
        child.bind_all('<Button-4>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Button-5>', lambda e: _on_mousewheel(e, child))
        child.bind_all('<Shift-Button-4>', lambda e: _on_shiftmouse(e, child))
        child.bind_all('<Shift-Button-5>', lambda e: _on_shiftmouse(e, child))

def _unbound_to_mousewheel(event, widget):
    if platform.system() == 'Windows' or platform.system() == 'Darwin':
        widget.unbind_all('<MouseWheel>')
        widget.unbind_all('<Shift-MouseWheel>')
    else:
        widget.unbind_all('<Button-4>')
        widget.unbind_all('<Button-5>')
        widget.unbind_all('<Shift-Button-4>')
        widget.unbind_all('<Shift-Button-5>')

def _on_mousewheel(event, widget):
    if platform.system() == 'Windows':
        widget.yview_scroll(-1*int(event.delta/120),'units')
    elif platform.system() == 'Darwin':
        widget.yview_scroll(-1*int(event.delta),'units')
    else:
        if event.num == 4:
            widget.yview_scroll(-1, 'units')
        elif event.num == 5:
            widget.yview_scroll(1, 'units')

def _on_shiftmouse(event, widget):
    if platform.system() == 'Windows':
        widget.xview_scroll(-1*int(event.delta/120), 'units')
    elif platform.system() == 'Darwin':
        widget.xview_scroll(-1*int(event.delta), 'units')
    else:
        if event.num == 4:
            widget.xview_scroll(-1, 'units')
        elif event.num == 5:
            widget.xview_scroll(1, 'units')

if __name__ == '__main__':
    vp_start_gui()





